Feature/#6-linksniuKonvertavimas-function
RokasAniss/vardas pull request #9
Opened 2020-11-29 19:34 UTC by cesn4

2020-11-29 21:12 UTC, RokasAniss requested changes

2020-11-29 21:12 UTC, RokasAniss commented on src/lib/linksnioKonvertavimas/linksnioKonvertavimas.ts
> +    e => {
biski antipaternas, `e` naudojamas trumpinys vietoj `event`, kai naudojamas su html elementu actionais. Geriau įvardinti tiksliau kas čia yra, šiuo atveju `galune`.

2020-11-29 22:01 UTC, RokasAniss requested changes

2020-11-29 22:01 UTC, RokasAniss commented on src/lib/linksnioKonvertavimas/linksnioKonvertavimas.ts
> +} from '../../constants/index';
Ar reikia index gale?

2020-11-29 23:22 UTC, cesn4 commented on src/lib/linksnioKonvertavimas/linksnioKonvertavimas.ts
> +} from '../../constants/index';
Nah :D

2020-11-30 06:53 UTC, RokasAniss approved these changes

2020-11-30 06:53 UTC, merged